import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import Nav from "@/components/Nav";
import { ReactLenis } from "lenis/react";
import Wordmark from "@/components/Wordmark";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const director = localFont({
  src: [
    {
      path: "../public/fonts/Director-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Director-Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-director",
});

const selecta = localFont({
  src: [
    {
      path: "../public/fonts/SelectaTrialUnlicensed-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/SelectaTrialUnlicensed-ThinItalic.woff2",
      weight: "100",
      style: "italic",
    },
    {
      path: "../public/fonts/SelectaTrialUnlicensed-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/SelectaTrialUnlicensed-LightItalic.woff2",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/fonts/SelectaTrialUnlicensed-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/SelectaTrialUnlicensed-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/SelectaTrialUnlicensed-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/SelectaTrialUnlicensed-MediumItalic.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/fonts/SelectaTrialUnlicensed-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/SelectaTrialUnlicensed-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/fonts/SelectaTrialUnlicensed-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/SelectaTrialUnlicensed-BlackItalic.woff2",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-selecta",
});

const univers = localFont({
  src: [
    {
      path: "../public/fonts/UniversNextPro-MediumCond.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/UniversNextPro-MediumCondIt.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/fonts/UniversNextPro-XBlackCond.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/UniversNextPro-XBlackCondIt.ttf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-univers",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${selecta.variable} ${director.variable} ${univers.variable} antialiased`}
    >
      {/* Lenis drives the page's own scrolling. Views with their own scroll
          container set up a scoped instance of their own — see ProjectDetail. */}
      <body className="">
        <ReactLenis root />
        {children}
        <Nav />
      </body>
    </html>
  );
}
